For expert review
DemienBlogan/SoftServe_Task01 pull request #1
Opened 2020-10-08 07:36 UTC by DemienBlogan

2020-10-08 17:18 UTC, Stepbura commented on StringList.c
> +	strcpy(newNode[0], str);
The potential null pointer is passed into 'strcpy' function. Inspect input arguments.

2020-10-08 17:20 UTC, Stepbura commented on StringList.c
> +	if (*list == NULL || list == NULL)
Please verify if 'str' is not null as well

2020-10-08 17:21 UTC, Stepbura commented on StringList.c
> +	if (*list == NULL || list == NULL)
Please verify if 'str' is not null as well

2020-10-08 17:23 UTC, Stepbura commented on StringList.c
> +				previousNode[1] = currectNode[1];
Dereferencing of the null pointer 'previousNode' might take place.

2020-10-08 17:24 UTC, Stepbura commented on StringList.c
> +			strcpy(currectNode[0], newStr);
The potential null pointer is passed into 'strcpy' function. Inspect input arguments.

2020-10-08 17:25 UTC, Stepbura requested changes
Please take a look my comments.

2020-10-09 08:33 UTC, DemienBlogan commented on StringList.c
> +	strcpy(newNode[0], str);
Solved. Thanks.

2020-10-09 08:33 UTC, DemienBlogan commented on StringList.c
> +	if (*list == NULL || list == NULL)
Solved. Thanks.

2020-10-09 08:34 UTC, DemienBlogan commented on StringList.c
> +	if (*list == NULL || list == NULL)
Solved. Thanks.

2020-10-09 08:34 UTC, DemienBlogan commented on StringList.c
> +				previousNode[1] = currectNode[1];
Solved. Thanks.

2020-10-09 08:34 UTC, DemienBlogan commented on StringList.c
> +			strcpy(currectNode[0], newStr);
Solved. Thanks.

2020-10-12 13:54 UTC, Stepbura approved these changes

2020-10-12 19:58 UTC, merged